services:
  db:
    container_name: db
    image: postgres:latest
    environment:
        POSTGRES_DB: ${DB_NAME_PROD}
        POSTGRES_USER: ${DB_USER_PROD}
        POSTGRES_PASSWORD: ${DB_PASS_PROD}
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
      - ./files:/files
    ports:
      - 5432:5432
    networks:
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - pgadmin_root_prefs:/root/.pgadmin
      - pgadmin_working_dir:/var/lib/pgadmin
      - ./files:/files
    ports:
      - 5050:5050
    networks:
      - db

  dbt:
    container_name: dbt
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - db
    volumes:
      - .:/app
    environment:
      DB_HOST_PROD: db
      DB_USER_PROD: postgres
      DB_PASS_PROD: admin
      DB_PORT_PROD: 5432
      DB_NAME_PROD: northwind_dbt
      DB_SCHEMA_PROD: public
      DB_THREADS_PROD: 1
      DB_TYPE_PROD: postgres
      DBT_PROFILES_DIR: /app

networks:
  db:
    driver: bridge

volumes:
  pgadmin_root_prefs:
    driver: local
  pgadmin_working_dir:
    driver: local
  postgresql_data:
    driver: local
  postgresql_bin:
    driver: local