
version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_dbt
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: northwind
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_dbt
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  dbt:
    build: .
    container_name: dbt_runner
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DBT_PROFILES_DIR: /app
    command: ["dbt", "run", "--profiles-dir", "/app"]

volumes:
  postgres_data: